services:
    database:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mydb

    manager:
        image: adminer:latest
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: database
            ADMINER_DEFAULT_USERNAME: root
            ADMINER_DEFAULT_PASSWORD: root
            ADMINER_DESIGN: pepa-linha
